In [2]:
import numpy as np

In [31]:
oneDArray = np.array([1, 2, 3, 4, 5]) # pass python list/tuple to .array() function
print(oneDArray)
print(oneDArray.ndim)
for i in oneDArray:
    print(i)

[1 2 3 4 5]
1
1
2
3
4
5


In [35]:
twoDArray = np.array([[1, 2, 3], [4, 5, 6]])
print(twoDArray)
print(twoDArray.ndim)
print(twoDArray[1])
print(twoDArray[1, 0])
print(twoDArray.shape) # returns tuple; x = 2, y = 3 (no. of elements)
for i in twoDArray:
    for j in i:
        print(j)

[[1 2 3]
 [4 5 6]]
2
[4 5 6]
4
(2, 3)
1
2
3
4
5
6


In [36]:
threeDArray = np.array([[[1, 2, 3], [-1, -2, -3]], [[4, 5, 6], [-4, -5, -6]]])
print(threeDArray)
print(threeDArray.ndim)
print(threeDArray[0])
print(threeDArray[1])
print(threeDArray[0,1])
print(threeDArray[0,1,0])
print('--')
for i in threeDArray:
    # print(i)
    for j in i:    # print(i)

        for k in j:
            print(k)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
3
[[ 1  2  3]
 [-1 -2 -3]]
[[ 4  5  6]
 [-4 -5 -6]]
[-1 -2 -3]
-1
--
1
2
3
-1
-2
-3
4
5
6
-4
-5
-6


In [28]:
h = np.array([[[1,2, 3, 4]]])
print(h)
print(h[0, 0, 0])

[[[1 2 3 4]]]
1


In [5]:
zerosArray = np.zeros(10)
print(zerosArray)
print(type(zerosArray))
zerosArray = zerosArray.astype(int)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0]


In [8]:
onesArray = np.ones(10)
print(onesArray) # each of them is a float
onesArray = onesArray.astype(int)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [9]:
fullArray = np.full(10, 5) 
print(fullArray)

[5 5 5 5 5 5 5 5 5 5]


In [25]:
# scalar operations

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix + 2)
print(matrix - 2)
print('--')
print(matrix * 2)
print('--')
print(matrix / 2) # for float
print(matrix // 2) # for int
print(matrix.T)

pythonList = [[1, 2, 3], [4, 5, 6]]
#print(pythonList)
#print(pythonList * 2) #list is concatenated w/ itself
#print(pythonList ** 2) # incompatible functions for list / int
# print(pythonList.T) # list object has no function .T

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
--
[[ 2  4  6]
 [ 8 10 12]]
--
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0 1 1]
 [2 2 3]]
[[1 4]
 [2 5]
 [3 6]]


AttributeError: 'list' object has no attribute 'T'

In [35]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[-1, -2, -3], [-4, -5, -6]])
#print(matrix1 + matrix2)
print(matrix1 / matrix2)
print((matrix1 / matrix2).astype(int))

pythonList1 = [[1, 2, 3], [4, 5, 6]]
pythonList2 = [[-1, -2, -3], [-4, -5, -6]]
#print(pythonList1 + pythonList2)

[[-1. -1. -1.]
 [-1. -1. -1.]]
[[-1 -1 -1]
 [-1 -1 -1]]


In [37]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [0,0,0]])
matrix2 = np.array([[-1, -2, -3], [-4, -5, -6], [0,0,0]])
np.matmul(matrix1, matrix2)

array([[ -9, -12, -15],
       [-24, -33, -42],
       [  0,   0,   0]])

In [44]:
# frequently used stat functions
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
np.min(matrix1)
np.max(matrix1)
np.sum(matrix1)
np.mean(matrix1)
np.std(matrix1)
np.median(matrix1)

3.5